### ISSUE TITLE
Tool is detected as a virus by Microsoft Defender

### ISSUE THREAD

**Issue by MiddleSiggy** [libretiny-eu/ltchiptool#49] opened 2024-12-17 16:42 UTC
Your tool is detected as : Trojan:Win32/Wacatac.B!ml

More Info:
webfile: C:\Install\ItChipTool\ltchiptool-v4.11.4.exe|https://objects.githubusercontent.com/github-production-release-asset-2e65be/519155917/c334efe9-46b4-43ea-8623-935603052e9a?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20241217%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241217T164037Z&X-Amz-Expires=300&X-Amz-Signature=f359696b11053e1c5b06f87171ac910704ef0403a20f0015e6706104b19c304d&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dltchiptool-v4.11.4.exe&response-content-type=application%2Foctet-stream|pid:42684,ProcessStart:133789272404247950

It seems that the v4.11.1 is not detected, BUT
v4.11.2 and v4.11.4 are detected as infected. 

So doing some further checking v4.11.1 is detected by multiple vendors as having an issue on VirusTotal:
Bkav Pro = W64.AIDetectMalware
Fortinet = W32/PossibleThreat
Jiangmin = TrojanSpy.Agent.afwu
**McAfee Scanner = Ti!EBCF3BF55DBF
Palo Alto Networks = Generic.ml**
SecureAge = Malicious
Skyhigh (SWG) = Artemis
Trellix (ENS) = Artemis!52F627335A9F

https://www.virustotal.com/gui/file/ebcf3bf55dbfe389512b4ba81200256a0256b846c7b9db05eea24322caa0530f/behavior

Might want to check things,

Thanks

**Comment by kuba2k2** [comment] 2024-12-17 16:58
Duplicate of #10.
See my comment: https://github.com/libretiny-eu/ltchiptool/issues/10#issuecomment-2408517796

**Closed by kuba2k2** 2024-12-17 16:58 UTC

**Comment by kuba2k2** [comment] 2024-12-17 17:00
Also note that the AV programs that detected the file are... hmm of questionable quality/popularity/reputation. No well-known software detected it as malware (this time...)
